// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qmgsbkfhytyuiueyqndz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFtZ3Nia2ZoeXR5dWl1ZXlxbmR6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1NTIzNDUsImV4cCI6MjA3MDEyODM0NX0.1I-vpb_yLEgjHJwjjWwvx_rYmo90K5ccbFcl1G5F054";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});